#!/usr/bin/env python3
"""CLI: expand a sweep YAML into per-cell run YAMLs.

Usage:
    python scripts/expand_sweep.py configs/sweeps/hp_alpha.yaml
    python scripts/expand_sweep.py configs/sweeps/hp_alpha.yaml --out-dir "${FITTEXT_RUNTIME_ROOT:-runs}/generated_configs"

Each generated YAML is a valid run config that can be passed directly to run.py.
Output files land under ``FITTEXT_RUNTIME_ROOT`` by default.
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

import yaml

# Ensure repo root is on the path
sys.path.insert(0, str(Path(__file__).parent.parent))

from toolbench.runner.sweep import expand_sweep, cell_to_run_yaml


def _parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    """Parse CLI arguments.

    Args:
        argv: Argument list (defaults to sys.argv[1:]).

    Returns:
        Parsed namespace.
    """
    parser = argparse.ArgumentParser(
        description="Expand a sweep YAML into per-cell run YAMLs.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument(
        "sweep_config",
        type=Path,
        help="Path to sweep YAML (e.g. configs/sweeps/hp_alpha.yaml).",
    )
    parser.add_argument(
        "--out-dir",
        type=Path,
        default=None,
        dest="out_dir",
        help="Output directory for generated YAMLs. "
        "Defaults to $FITTEXT_RUNTIME_ROOT/generated_configs.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print cell list without writing files.",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    """Main entry point.

    Args:
        argv: Argument list (defaults to sys.argv[1:]).

    Returns:
        Exit code.
    """
    args = _parse_args(argv)

    repo_root = Path(__file__).parent.parent
    if args.out_dir is None:
        out_dir = Path(os.environ.get("FITTEXT_RUNTIME_ROOT", str(repo_root / "runs"))) / "generated_configs"
    else:
        out_dir = args.out_dir

    cells = expand_sweep(args.sweep_config)
    print(f"Sweep '{args.sweep_config.stem}': {len(cells)} cells")

    if args.dry_run:
        for i, cell in enumerate(cells):
            print(f"  [{i:03d}] {cell['cell_id']}")
        return 0

    out_dir.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    try:
        source_label = args.sweep_config.resolve().relative_to(repo_root.resolve()).as_posix()
    except ValueError:
        source_label = args.sweep_config.name

    for cell in cells:
        run_dict = cell_to_run_yaml(cell)
        # Add header comment
        yaml_str = (
            f"# Generated by expand_sweep.py from {source_label}\n"
            f"# cell_id: {cell['cell_id']}\n"
            f"# overrides: {cell['overrides']}\n"
        )
        yaml_str += yaml.dump(run_dict, default_flow_style=False, sort_keys=True)
        out_path = out_dir / f"{cell['suggested_filename']}.yaml"
        out_path.write_text(yaml_str)
        written.append(out_path)
        print(f"  wrote: {out_path.relative_to(repo_root)}")

    print(f"\n{len(written)} files written to {out_dir.relative_to(repo_root)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
